spring:
  redis:
    database: 4
    host: tech.zhiyis.com
    port: 8084
    password: 123456
    timeout: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 10
        max-wait: 10000
        max-active: 10
